# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM tomcat:alpine

COPY ./target/pdm-projeto-webapp-1.0-SNAPSHOT.war $CATALINA_HOME/webapps/pdm-projeto-webapp.war

